### ISSUE TITLE
We should flatten input files

### ISSUE THREAD

**Issue by ivan-wolf** [detailnet/imagemagick-scripts#4]
PSDs and TIFFs may be layered...

**Comment by curzio-della-santa** [comment]
@ivan-wolf 

For this issue there are a few things to consider, due to the low support of PSD support in convert.

My suggestion is to use as described in this comment http://www.imagemagick.org/discourse-server/viewtopic.php?t=20400#p81401

One example:
https://s3-eu-west-1.amazonaws.com/uploads-eu.hipchat.com/106427/784210/3ubB2D1NrqQSR5x/1001348_Konfetti_Kugel_Superiore.psd

with flatten:
![psd](https://cloud.githubusercontent.com/assets/7221909/6351380/61fe489c-bc3b-11e4-87e6-d161b55e2517.jpeg)
(also very slow)

with layer 0:
![psd](https://cloud.githubusercontent.com/assets/7221909/6351403/a5caa53e-bc3b-11e4-8b89-916b420c83e5.jpeg)

Tested also with a multi-layer tiff (same image saved from adobe), bough -flatten and layer [0]  produced same image ... (note. also gimp does not permits a multi-layer tiff .. )

I'll implement with layer 0 as default ..
